apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: us-east-1

vpc:
  id: vpc-0c9d26e5f4b6ee984
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-017e31216c1f9a569
      my-new-stack-PublicSubnet02:
        id: subnet-07533acb7ebf9c655
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-0b778015b72e104d1
      my-new-stack-PrivateSubnet02:
        id: subnet-0300cb387c48dfc9c

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1